import { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
  // Deletes ALL existing entries
  await knex("businesses").del();

  // Inserts seed entries
  await knex("businesses").insert([
    {
      description: "A cozy family-owned coffee shop serving organic brews.",
      pairing_uri_encrypted: null,
      wallet_created: false,
      wallet_id: null,
      business_name: "Bean & Brew",
      address: "123 Main St",
      city: "Greenville",
      state: "SC",
      phone: "864-555-0001",
      email: "info@beanandbrew.com",
      email_verified: true,
      website: "https://beanandbrew.com",
      logo_url: "https://images.unsplash.com/photo-1509042239860-f550ce710b93",
      latitude: 34.8526,
      longitude: -82.394,
      owner_id: "1",
      category_id: 1,
    },
    {
      description: "A boutique barber shop with vintage vibes.",
      pairing_uri_encrypted: null,
      wallet_created: false,
      wallet_id: null,
      business_name: "The Vintage Cut",
      address: "456 Barber Blvd",
      city: "Greenville",
      state: "SC",
      phone: "864-555-0022",
      email: "hello@vintagecut.com",
      email_verified: true,
      website: "https://vintagecut.com",
      logo_url: "https://images.unsplash.com/photo-1588776814546-ec7cf019c07f",
      latitude: 34.8541,
      longitude: -82.3923,
      owner_id: "2",
      category_id: 2,
    },
    {
      description: "Handmade pastries and fresh local bread daily.",
      pairing_uri_encrypted: null,
      wallet_created: false,
      wallet_id: null,
      business_name: "Rise & Shine Bakery",
      address: "789 Dough St",
      city: "Greenville",
      state: "SC",
      phone: "864-555-0033",
      email: "orders@risenshine.com",
      email_verified: false,
      website: "https://riseandshinebakery.com",
      logo_url: "https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38",
      latitude: 34.8512,
      longitude: -82.3965,
      owner_id: "3",
      category_id: 3,
    },
    {
      description: "Local gym with 24/7 access and group classes.",
      pairing_uri_encrypted: null,
      wallet_created: false,
      wallet_id: null,
      business_name: "Iron Temple",
      address: "321 Fitness Ln",
      city: "Greenville",
      state: "SC",
      phone: "864-555-0044",
      email: "info@irontemplegym.com",
      email_verified: true,
      website: "https://irontemplegym.com",
      logo_url: "https://images.unsplash.com/photo-1571019613914-85f342c1d14e",
      latitude: 34.85,
      longitude: -82.393,
      owner_id: "4",
      category_id: 4,
    },
    {
      description: "Tech support and gadget repair, fast and friendly.",
      pairing_uri_encrypted: null,
      wallet_created: false,
      wallet_id: null,
      business_name: "Tech Savvy",
      address: "111 Tech Ave",
      city: "Greenville",
      state: "SC",
      phone: "864-555-0055",
      email: "support@techsavvy.com",
      email_verified: true,
      website: "https://techsavvy.com",
      logo_url: "https://images.unsplash.com/photo-1581093588401-3a8b4c07fd8a",
      latitude: 34.855,
      longitude: -82.391,
      owner_id: "5",
      category_id: 5,
    },
    {
      description: "Organic smoothie bar with seasonal ingredients.",
      pairing_uri_encrypted: null,
      wallet_created: false,
      wallet_id: null,
      business_name: "Green Sip",
      address: "222 Vitality Blvd",
      city: "Greenville",
      state: "SC",
      phone: "864-555-0066",
      email: "fresh@greensip.com",
      email_verified: false,
      website: "https://greensip.com",
      logo_url: "https://images.unsplash.com/photo-1585238341986-2d2b0e63d3a5",
      latitude: 34.857,
      longitude: -82.3955,
      owner_id: "6",
      category_id: 6,
    },
    {
      description: "Custom woodworking studio and gallery.",
      pairing_uri_encrypted: null,
      wallet_created: false,
      wallet_id: null,
      business_name: "Grain & Glory",
      address: "333 Artisan Way",
      city: "Greenville",
      state: "SC",
      phone: "864-555-0077",
      email: "hello@grainandglory.com",
      email_verified: true,
      website: "https://grainandglory.com",
      logo_url: "https://images.unsplash.com/photo-1605810230434-7631b7112a6c",
      latitude: 34.8585,
      longitude: -82.3975,
      owner_id: "7",
      category_id: 7,
    },
    {
      description: "Music lessons and instrument repair for all ages.",
      pairing_uri_encrypted: null,
      wallet_created: false,
      wallet_id: null,
      business_name: "Sound Roots",
      address: "444 Harmony Rd",
      city: "Greenville",
      state: "SC",
      phone: "864-555-0088",
      email: "info@soundroots.com",
      email_verified: false,
      website: "https://soundroots.com",
      logo_url: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4",
      latitude: 34.859,
      longitude: -82.3985,
      owner_id: "8",
      category_id: 8,
    },
    {
      description: "Locally sourced produce and artisan goods.",
      pairing_uri_encrypted: null,
      wallet_created: false,
      wallet_id: null,
      business_name: "Greenville Market Co.",
      address: "555 Fresh St",
      city: "Greenville",
      state: "SC",
      phone: "864-555-0099",
      email: "info@greenvillemarket.co",
      email_verified: true,
      website: "https://greenvillemarket.co",
      logo_url: "https://images.unsplash.com/photo-1570197781534-d4f9f3e0dbb0",
      latitude: 34.86,
      longitude: -82.399,
      owner_id: "9",
      category_id: 9,
    },
  ]);
}
