import { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
  // Deletes ALL existing entries
  await knex("businesses").del();

  // Inserts seed entries
  await knex("businesses").insert([
    {
      description: "A cozy family-owned coffee shop serving organic brews.",
      pairing_uri_encrypted: null,
      wallet_created: false,
      wallet_id: null,
      business_name: "Bean & Brew",
      address: "123 Main St",
      city: "Greenville",
      state: "SC",
      phone: "864-555-0001",
      email: "info@beanandbrew.com",
      email_verified: true,
      website: "https://beanandbrew.com",
      logo_url: "https://images.unsplash.com/photo-1509042239860-f550ce710b93",
      latitude: 34.8526,
      longitude: -82.394,
      owner_id: "1",
      category_id: 1,
      hiring_promoters: true,
    },
    {
      description: "A boutique barber shop with vintage vibes.",
      pairing_uri_encrypted: null,
      wallet_created: false,
      wallet_id: null,
      business_name: "The Vintage Cut",
      address: "456 Barber Blvd",
      city: "Greenville",
      state: "SC",
      phone: "864-555-0022",
      email: "hello@vintagecut.com",
      email_verified: true,
      website: "https://vintagecut.com",
      logo_url: "https://images.unsplash.com/photo-1585747860715-2ba37e788b70",
      latitude: 34.8541,
      longitude: -82.3923,
      owner_id: "2",
      category_id: 2,
      hiring_promoters: true,
    },
    {
      description: "Handmade pastries and fresh local bread daily.",
      pairing_uri_encrypted: null,
      wallet_created: false,
      wallet_id: null,
      business_name: "Rise & Shine Bakery",
      address: "789 Dough St",
      city: "Greenville",
      state: "SC",
      phone: "864-555-0033",
      email: "orders@risenshine.com",
      email_verified: false,
      website: "https://riseandshinebakery.com",
      logo_url: "https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38",
      latitude: 34.8512,
      longitude: -82.3965,
      owner_id: "3",
      category_id: 3,
      hiring_promoters: true,
    },
    {
      description: "Local gym with 24/7 access and group classes.",
      pairing_uri_encrypted: null,
      wallet_created: false,
      wallet_id: null,
      business_name: "Iron Temple",
      address: "321 Fitness Ln",
      city: "Greenville",
      state: "SC",
      phone: "864-555-0044",
      email: "info@irontemplegym.com",
      email_verified: true,
      website: "https://irontemplegym.com",
      logo_url: "https://images.unsplash.com/photo-1716915372382-3c51d0013b56",
      latitude: 34.85,
      longitude: -82.393,
      owner_id: "4",
      category_id: 4,
      hiring_promoters: true,
    },
    {
      description: "Tech support and gadget repair, fast and friendly.",
      pairing_uri_encrypted: null,
      wallet_created: false,
      wallet_id: null,
      business_name: "Tech Savvy",
      address: "111 Tech Ave",
      city: "Greenville",
      state: "SC",
      phone: "864-555-0055",
      email: "support@techsavvy.com",
      email_verified: true,
      website: "https://techsavvy.com",
      logo_url:
        "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRlY2glMjBzdXBwb3J0fGVufDB8fDB8fHww",
      latitude: 34.855,
      longitude: -82.391,
      owner_id: "5",
      category_id: 5,
      hiring_promoters: true,
    },
    {
      description: "Organic smoothie bar with seasonal ingredients.",
      pairing_uri_encrypted: null,
      wallet_created: false,
      wallet_id: null,
      business_name: "Green Sip",
      address: "222 Vitality Blvd",
      city: "Greenville",
      state: "SC",
      phone: "864-555-0066",
      email: "fresh@greensip.com",
      email_verified: false,
      website: "https://greensip.com",
      logo_url:
        "https://images.unsplash.com/photo-1633777050410-4dc5d0b23166?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fG9yZ2FuaWMlMjBzbW9vdGhpZXxlbnwwfHwwfHx8MA%3D%3D",
      latitude: 34.857,
      longitude: -82.3955,
      owner_id: "6",
      category_id: 6,
      hiring_promoters: true,
    },
    {
      description: "Custom woodworking studio and gallery.",
      pairing_uri_encrypted: null,
      wallet_created: false,
      wallet_id: null,
      business_name: "Grain & Glory",
      address: "333 Artisan Way",
      city: "Greenville",
      state: "SC",
      phone: "864-555-0077",
      email: "hello@grainandglory.com",
      email_verified: true,
      website: "https://grainandglory.com",
      logo_url:
        "https://images.unsplash.com/photo-1629085281900-455f2f1fc5ab?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGxvY2FsJTIwY2FycGVudGVyfGVufDB8fDB8fHww",
      latitude: 34.8585,
      longitude: -82.3975,
      owner_id: "7",
      category_id: 7,
      hiring_promoters: false,
    },
    {
      description: "Music lessons and instrument repair for all ages.",
      pairing_uri_encrypted: null,
      wallet_created: false,
      wallet_id: null,
      business_name: "Sound Roots",
      address: "444 Harmony Rd",
      city: "Greenville",
      state: "SC",
      phone: "864-555-0088",
      email: "info@soundroots.com",
      email_verified: false,
      website: "https://soundroots.com",
      logo_url: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4",
      latitude: 34.859,
      longitude: -82.3985,
      owner_id: "8",
      category_id: 8,
      hiring_promoters: true,
    },
    {
      description: "Locally sourced produce and artisan goods.",
      pairing_uri_encrypted: null,
      wallet_created: false,
      wallet_id: null,
      business_name: "Greenville Market Co.",
      address: "555 Fresh St",
      city: "Greenville",
      state: "SC",
      phone: "864-555-0099",
      email: "info@greenvillemarket.co",
      email_verified: true,
      website: "https://greenvillemarket.co",
      logo_url:
        "https://images.unsplash.com/photo-1506484381205-f7945653044d?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bG9jYWwlMjBmYXJtZXJzJTIwbWFya2V0fGVufDB8fDB8fHww",
      latitude: 34.86,
      longitude: -82.399,
      owner_id: "9",
      category_id: 9,
      hiring_promoters: false,
    },
  ]);
}
